# Generated by Django 4.2.7 on 2023-12-05 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.menu'),
        ),
    ]
