# Generated by Django 4.2.7 on 2023-12-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_menu_menu_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_link',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
